modLoader="javafml"
loaderVersion="[${javafml_min},${javafml_max})"
issueTrackerURL="http://github.com/HalogenMods/Chlorine/issues"
license="GNU Lesser General Public License v3.0"

[[mods]]
    modId="chlorine"
    version="${version}"
    displayName="Chlorine"
    authors="JellySquid, hanetzer"
    description='''
        Chlorine is an free and open-source optimization mod for Minecraft which improves frame rates and reduces lag spikes.
        Based on Sodium version ${sodium_version}
        '''
    credits="JellySquid, hanetzer"

[[dependencies.chlorine]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_min},${forge_max})"
    ordering="NONE"
    side="BOTH"

[[dependency.chlorine]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_min},${minecraft_max})"
    ordering="NONE"
    side="BOTH"